version: '3'
services:
  aleph-scoring:
    build: .
    image: aleph-scoring:latest
    command: "run-on-schedule --format json"
    environment:
      SENTRY_DSN: ""
    volumes:
      - ./exports:/exports
