name: Python application

on:
  push:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Lint with black
      run: |
        hatch run linting:style
    - name: Typing check
      run: |
        hatch run typing:typing
